# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [8]:
def check(l1):

  if l1[0] == l1[len(l1)-1]:
    return True
  else:
    return False

# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

print(check(numbers_x))
print(check(numbers_y))
# len(numbers_x)
# numbers_x[len(numbers_x)-1]
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True


# numbers_y = [75, 65, 35, 75, 30]
# result is False

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [10]:
#code here
import numpy as np

arr1=np.arange(0,9).reshape(3,3)
print(arr1)
arr2=np.arange(12,21).reshape(3,3)
print(arr2)
sum=arr1+arr2
print('sum of two arrays: ',sum)
mul=arr1+arr2
print('product of two arrays: ',mul)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[12 13 14]
 [15 16 17]
 [18 19 20]]
sum of two arrays:  [[12 14 16]
 [18 20 22]
 [24 26 28]]
product of two arrays:  [[12 14 16]
 [18 20 22]
 [24 26 28]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [19]:
#code here
arr1=np.arange(0,12)
print(arr1)
print(arr1.reshape(3,4))

arr1=arr1.reshape(3,4)
arr2=np.arange(12,24).reshape(3,4)
horizontal=np.hstack((arr1,arr2))
print('After horizontal stack: ',horizontal)

vertical=np.vstack((arr1,arr2))
print('After vertical stack: ',vertical)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After horizontal stack:  [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
After vertical stack:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [21]:
#Code here
shopping_cart=[]
available=['hafsa','arooj','sharam','aqal','gherat']
check=True
while check:
  print(available)
  key=input('Enter the index corresponding to thing u want')
  if key=='q':
    break
  key=int(key)
  shopping_cart.append(available[key])
  print('New product ',available[key],' has been added to ur shopping cart')
  a=input('Do you want to continue adding to cart?(y/n)')
  if a=='n':
    print("Thankyou for shopping have a great time!")
    check=False

print('your shopping cart: ',shopping_cart)

['hafsa', 'arroj', 'sharam', 'aqal', 'gherat']
Enter the index corresponding to thing u want0
New product  hafsa  has been added to ur shopping cart
Do you want to continue adding to cart?(y/n)y
['hafsa', 'arroj', 'sharam', 'aqal', 'gherat']
Enter the index corresponding to thing u want4
New product  gherat  has been added to ur shopping cart
Do you want to continue adding to cart?(y/n)n
Thankyou for shopping have a great time!
your shopping cart  ['hafsa', 'gherat']


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [31]:
#code here
def classify_emails(emails):
  important=[]
  promotions=[]
  spam=[]
  for i in emails:
    if 'important' in i:
      important.append(i)
    elif 'promotions' or 'deals' in i:
      promotions.append(i)
    elif 'spam' in i:
      spam.append(i)
  return important,promotions,spam
mails=['this mail is important','this mail is promotions','this mail is spam','this mail is important','this mail is promotions','this mail is spam']
a=classify_emails(mails)
print(a)

(['this mail is important', 'this mail is important'], ['this mail is promotions', 'this mail is spam', 'this mail is promotions', 'this mail is spam'], [])


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [34]:
#code here
translation={
    'hi':'hola',
    'thankyou':'gracias',
    'friend': 'amigo'
}
check=True
while check:
  eng=input('Enter an english word')
  if eng in translation.keys():
   print('Spanish translation of ',eng," is ",translation[eng])
  else:
    break

  a=input('Do you want to continue?(y/n)')
  if a=='n':
    check=False


Enter an english wordhi
Spanish translation of hi is hola
Do you want to continue?(y/n)n


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [36]:
import pandas as pd
data=pd.read_csv(' https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')
df=pd.DataFrame(data)
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [38]:
df.Global_Sales.sum()

8920.44

In [44]:
df.loc[df['Global_Sales'].idxmax()]

Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object

In [46]:

print('Average sales for NA ',df.NA_Sales.mean())
print('Average sales for JP ',df.JP_Sales.mean())
print('Average sales for Other ',df.Other_Sales.mean())

Average sales for NA  0.26466742981082064
Average sales for JP  0.077781660441017
Average sales for Other  0.0480630196409206


In [47]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [49]:
genre_sales = df.groupby('Genre')['Global_Sales'].sum()
sorted_genres = genre_sales.sort_values(ascending=False)
sorted_genres.head(5)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [52]:
print('Average sales for NA ',df.NA_Sales.sum())
print('Average sales for JP ',df.JP_Sales.sum())
print('Average sales for Other ',df.Other_Sales.sum())
df.groupby('Genre')['NA_Sales'].sum().idxmax()


Average sales for NA  4392.950000000001
Average sales for JP  1291.0200000000002
Average sales for Other  797.7500000000001


'Action'

In [53]:
platform_sales = df.groupby('Platform')['Global_Sales'].sum()
sorted_platforms = platform_sales.sort_values(ascending=False)
sorted_platforms.head(3)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [54]:
df['Market_Share'] = (df['Global_Sales'] / df['Global_Sales'].sum()) * 100
df[['Genre', 'Market_Share']]

Genre  Market_Share
0            Sports      0.927533
1          Platform      0.451099
2            Racing      0.401550
3            Sports      0.369937
4      Role-Playing      0.351664
...             ...           ...
16593      Platform      0.000112
16594       Shooter      0.000112
16595        Racing      0.000112
16596        Puzzle      0.000112
16597      Platform      0.000112

[16598 rows x 2 columns]

In [55]:
df['NA_Sales'].corr(df['EU_Sales'])

0.7677267483702631